### ISSUE TITLE
Dynamic SAML Attribute Interception Script 

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxShibboleth#71]
We don't like to use shib dynamic attribute scripts, because they are hard to maintain. Ideally, this kind of script would be a standard interception script. Is there any way to connect Shibboleth to call an interception script defined in oxTrust?

**Comment by malotian** [comment]
sample/example to understand enhancement 

let say user’s age is stored as number. and we wanted to release like Toddler/Young/Adult/Old etc etc (instead of number)

Idea is to be able to write in python like other scripts (in friendly manner)
where user gets hashmap of attributes in a function call, user can edit map in python and modified will be released by shibb

**Comment by malotian** [comment]
research around using shibboleth profile interceptor

```
public class OutboundMessageProcessor extends AbstractProfileAction {
	@Override
	protected void doExecute(@Nonnull final ProfileRequestContext profileRequestContext) {

	}
}
```

**Comment by malotian** [comment]
Reseraching on https://wiki.shibboleth.net/confluence/display/IDP30/ProfileInterceptConfiguration

**Comment by sandovalezequiel** [comment]
do we have any updates on this guys? do you need any additional information or something that we can help to move forward this?

**Comment by yurem** [comment]
I see. These points explains target and also answer on question where to call this script. I'm going to reassign this issue to myself

**Comment by ggallard** [comment]
Based on our observations, IDP is getting the attributes directly from LDAP/CB, not from the id_token or userinfo endpoint.
https://github.com/GluuFederation/oxTrust/blob/master/configuration/src/main/resources/META-INF/shibboleth3/idp/attribute-resolver.xml.vm
Am I missing something?

If it were getting those attributes from the returning id_token, it would be much easier, since we already have (OIDC) dynamic claims solved.

**Comment by malotian** [comment]
@yurem I have alreday reserached about how to update attributes, after authn. Please advise me how I can integrate it with Jython

**Comment by yurem** [comment]
@ggallard Currently it should works in this way:
SP -> IDP -> IDP (oxAuth plugin) -> oxAuth -> IDP (oxAuth plugin) -> IDP (map id_token claim to IDP user principal)-> SP

It maps claims [here](https://github.com/GluuFederation/shib-oxauth-authn3/blob/master/src/main/java/org/gluu/idp/externalauth/ShibOxAuthAuthServlet.java#L176) using translator.

Here is translator [code](https://github.com/GluuFederation/shib-oxauth-authn3/blob/master/src/main/java/org/gluu/idp/externalauth/AuthenticatedNameTranslator.java#L50).

**Comment by yurem** [comment]
These classes have many debug output. You can enable DEBUG log level in IDP for `org.gluu.idp` to see how it works

**Comment by yurem** [comment]
In any case we will add new script to allow map claims to IDP client credentials externally. It should be called from translator class

**Comment by malotian** [comment]
@yurem are you saying that we will introduce interception script in translation only ? But I guess shibboleth also make connections to LDAP/User Directories for fetching additional attributes.

And If I understood correctly idea of this issue was to manipulate the attribute name and values, once authentication is done, just before releasing those in assertion.

If above is true, I have already looked at the way to do this  - https://github.com/malotian/malotian-shibboleth-release-attributes-post-processor

**Comment by nynymike** [comment]
I think you're on the right track. Can the post-processor call an interception script? What if different SP's need to call different scripts? How would we signal from the SP config in oxTrust?

**Comment by malotian** [comment]
> I think you're on the right track. 
Good to Know

> Can the post-processor call an interception script? 
Yes post processor can call any java code, i have done a P.o.C. to call a java class/function.
now from Java using jython we can route it to python scripts

> What if different SP's need to call different scripts? How would we signal from the SP config in oxTrust?
I guess that can be handled some how by passing context (may be script name) to main script - single entry point configured at shibboleth,

and inside main script, we will receive context (another script name) etc etc... I would say these are doable on eot another way.

I guess main point is connecting jython, python interface in java code.

https://github.com/malotian/malotian-shibboleth-release-attributes-post-processor/blob/master/src/main/java/com/malotian/shibboleth/idp/consent/flow/ar/impl/ReleaseAttributesPostProcessor.java

reda this code, here just to modify i have removed - givenName
and added/updated - surname

just to do p.oc. modification before embedding into assertion.
-------------------------------------------------------------------
_Now what is left is, to pass on attribute map to python script from this java code.
python code will do modifications to attributes
then java code will receive modified attributes (from python), and finally those will be used to for assertion_

@yurem here I need your help - to pass on attribute map to python script from this java code

**Comment by malotian** [comment]
@yurem could please read above, and need your quick guidance to integrate with jython, shibb side is more of ready. needs to be integrated to jython and frontend.

**Comment by yurem** [comment]
b8f39a085f2af5280871bc539002297cf8e66185

**Comment by yurem** [comment]
@malotian I'm planning to finish tomorrow custom script update to allow reuse it in IDP.

We can split our work to work on it in parallel. 

We can do next:
1. Create Idp custom script manager using xml like this:
```
     <bean id="gluuIdpCustomScriptManager"
          class="org.gluu.idp.script.service.IdpCustomScriptManager">
        <constructor-arg name="configurationFactory" value="#{idpConfigurationFactory.instance()}" />
    </bean>
```
2. Merge your code into `https://github.com/GluuFederation/shib-oxauth-authn3/tree/master/src/main/java/org/gluu/idp`

3. Call from your code `gluuIdpCustomScriptManager.getIdpExternalScriptService()` to get script service. 

4. Call `IdpExternalScriptService.executeExternalUpdateAttributesMethod` with `context`.

5. Create context bean with all beans which needed in script.

**Comment by yurem** [comment]
Here is [sample](https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/gluu/oxauth/service/external/context/ConsentGatheringContext.java) of contex object which we use in oxAuth.

**Comment by yurem** [comment]
Here is [sample](https://github.com/GluuFederation/community-edition-setup/blob/master/static/extension/idp/SampleScript.py) idp script.

`IdpExternalScriptService.executeExternalUpdateAttributesMethod` should call this script `updateAttributes` method with context object.

**Comment by yurem** [comment]
@malotian I've finish work on standalone custom script manager. Here is [sample ](https://github.com/GluuFederation/oxCore/blob/master/core-script/src/test/java/org/gluu/service/custom/script/test/StandaloneCustomScriptManagerTest.java) how to use it.

**Comment by yurem** [comment]
`IdpCustomScriptManager` is ready too. Her is [code](https://github.com/GluuFederation/shib-oxauth-authn3/blob/master/src/main/java/org/gluu/idp/script/service/IdpCustomScriptManager.java).

Can you call it as specified in this [message](https://github.com/GluuFederation/oxShibboleth/issues/71#issuecomment-646019846)?

**Comment by yurem** [comment]
https://github.com/GluuFederation/oxShibboleth/commit/b2e97b2f5279994bb273cf2fc58dca1cc7c9d5cf

**Comment by yurem** [comment]
I've finish work on updates. All components works well. There is only one issue. IDP not call our bean. @malotian I've added call from place which you mentioned. It's path [61](https://github.com/GluuFederation/oxShibboleth/blob/master/static/src/main/patches/61.release-attributes-post-processor.patch). Additionally I've added path [62](https://github.com/GluuFederation/oxShibboleth/blob/master/static/src/main/patches/62.intercept-release-attributes.patch) when I tried to find why IDP not call it. Did you shared all xml spring changes?

**Comment by malotian** [comment]
> I've finished work on updates. All components works well. There is only one issue. IDP not call our bean. @malotian I've added call from place which you mentioned. It's path [61](https://github.com/GluuFederation/oxShibboleth/blob/master/static/src/main/patches/61.release-attributes-post-processor.patch). Additionally I've added path [62](https://github.com/GluuFederation/oxShibboleth/blob/master/static/src/main/patches/62.intercept-release-attributes.patch) when I tried to find why IDP not call it. Did you shared all xml spring changes?

Great yuriy, I will look at this soon. should be working soon

**Comment by yurem** [comment]
@malotian yes, sure. Take your time

**Comment by malotian** [comment]
@yurem  please get “jython-ntegration” branch for oxShibboleth & shib-oxauth-authn3, and 
then add  `p:postAuthenticationFlows="#{{'attribute-release', 'malotian-release-attributes-post-processor'}}" ` to `SAML.SSO` bean inside `relying-party.xml`

e.g.

`<bean parent="SAML2.SSO" p:postAuthenticationFlows="#{{'attribute-release', 'malotian-release-attributes-post-processor'}}" />`

this update to `relying-party.xml` we will do via gui (velocity templates), but lets test in principle first

**Comment by yurem** [comment]
I've build idp.war from `jython-integration` an applied this update:
```
--- relying-party.xml.orig      2020-08-28 11:44:45.973887293 -0700
+++ relying-party.xml   2020-08-28 11:44:34.492052731 -0700
@@ -49,6 +49,7 @@
                       p:signResponsesPredicate-ref="SignNoIntegrity"
                       p:signAssertions="false"
                       p:encryptNameIDs="false"
+                      p:postAuthenticationFlows="#{{'attribute-release', 'gluu-release-attributes-post-processor'}}"
                       p:encryptAssertionsPredicate-ref="EncryptNoConfidentiality" />

                 <bean parent="SAML2.ECP"
```

But it still not call script method

**Comment by yurem** [comment]
Maybe something else is needed?

**Comment by yurem** [comment]
Can you merge your changes to branches version_4.2.1 to allow simply install idp.war without manual changes?

**Comment by yurem** [comment]
https://github.com/GluuFederation/community-edition-setup/blob/version_4.2.1/static/extension/idp/SampleScript.py#L99

**Comment by yurem** [comment]
![image](https://user-images.githubusercontent.com/6104200/92275611-0e73ed80-eef8-11ea-8cd1-929256af0637.png)
